# Generated by Django 4.0.6 on 2022-07-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='enail',
            new_name='email',
        ),
    ]
